site_name: Rive Tester Documentation
site_description: Interactive Rive file parser, inspector, and debugging tool
site_author: IVG Design
site_url: https://ivg-design.github.io/rive_dev_playground/
use_directory_urls: false

repo_name: ivg-design/rive_dev_playground
repo_url: https://github.com/ivg-design/rive_dev_playground
edit_uri: edit/main/source_docs/

theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - toc.follow
    - content.code.copy
    - content.code.select
    - content.action.edit
    - content.action.view

plugins:
  - search
  - minify:
      minify_html: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - materialx.emoji.twemoji
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ivg-design/rive_dev_playground
    - icon: fontawesome/solid/globe
      link: https://ivg-design.github.io/rive_dev_playground/
  generator: false

extra_css:
  - css/custom.css

nav:
  - Home: index.md
  - Getting Started:
      - Quick Start: guide/quick-start.md
      - Installation: guide/installation.md
  - User Guide:
      - User Guide: guide/user-guide.md
      - Asset Manager: guide/asset-manager.md
  - Advanced:
      - Debugging: advanced/debugging.md
      - Debugger Fixes: advanced/debugger-fixes.md
      - Runtime Controls: advanced/runtime-controls.md
      - Event Mapper: advanced/event-mapper.md
  - Development:
      - Versioning: development/versioning.md
  - Deployment:
      - GitHub Pages: deployment/github-pages.md
      - Deployment Guide: deployment/deployment.md

site_dir: mkdocs_site
docs_dir: source_docs
