/**
 * Application version information
 * Auto-generated by semantic release workflow
 */
export const VERSION = '1.0.1';
export const BUILD_DATE = '2025-05-27T08:57:01Z';
export const BUILD_COMMIT = '9bcc5bbafc29bb7a90921a4ae3d42bf3bca86b5f';

// Display version in console
console.log(`🎮 Rive Playground v${VERSION} - Built ${BUILD_DATE}`);
