/**
 * Application version information
 * Auto-generated by semantic release workflow
 */
export const VERSION = '1.4.6';
export const BUILD_DATE = '2025-06-06T16:01:45Z';
export const BUILD_COMMIT = 'dffb839c8602558351b9c6c83d8f2cf6fde20df3';
// Display version in console
console.log(`🎮 Rive Playground v${VERSION} - Built ${BUILD_DATE}`);
