/**
 * Application version information
 * Auto-generated by semantic release workflow
 */
export const VERSION = '1.4.2';
export const BUILD_DATE = '2025-05-30T13:33:25Z';
export const BUILD_COMMIT = 'bb14c9c94fee55d7867e5f78e95265acd781ddd5';
// Display version in console
console.log(`🎮 Rive Playground v${VERSION} - Built ${BUILD_DATE}`);
